name: "Continuous Deployment"
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: IngSis-Grupo1-2024
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/snippet-permission